### ISSUE TITLE
Publish 2.1.0 to npm

### ISSUE THREAD

**Issue by stephen304** [rtc-io/rtc-pluggable-signaller#2]
I'm trying to use rtc-quickconnect, but the install fails because down the dependency chain, rtc-pluggable-signaller depends on ws@0.7.2, which doesn't install properly because of its dependencies and node-gyp. 

Here is the abridged dependency tree:

```
└─┬ rtc-quickconnect@5.2.1 
  ├─┬ rtc-pluggable-signaller@2.0.1 
  │ └─┬ rtc-switchboard-messenger@1.2.0 
  │   └─┬ messenger-ws@2.0.2 
  │     ├─┬ ws@0.7.2 
```

I checked up the dependency tree and every dependency has updated their dependencies - rtc-pluggable-signaller@2.1.0 uses rtc-switchboard-messenger@2.0.3 which uses messenger-ws@3.0.1 which uses ws@1.0.0.

The only problem is that rtc-quickconnect is still using rtc-pluggable-signaller@2.0.1 because it's the latest. As soon as rtc-pluggable-signaller@2.1.0 is published, rtc-quickconnect can update this dependency and it will build properly. I have tested this by cloning rtc-pluggable-signaller@2.1.0 and using npm link, then editing rtc-quickconnect to depend on 2.1.0 and it completely fixes the issue with doing npm install.

I hope this makes sense and I hope 2.1.0 can be published soon.

**Comment by nathanoehlman** [comment]
Hi @stephen304 - I've published `2.1.0`. Sorry it wasn't already published - I needed to get some NPM permissions a couple of weeks back when I made the change, and then promptly forgot about.

Cheers
